In [1]:
import numpy as np
import pandas as pd

# Prep the data

In [2]:
data_preprocessed_wrong_order = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed_wrong_order.head(10)

Reason_1  Reason_2  Reason_3  Reason_4  ID        Date  \
0         0         0         0         1  11  2015-07-07   
1         0         0         0         0  36  2015-07-14   
2         0         0         0         1   3  2015-07-15   
3         1         0         0         0   7  2015-07-16   
4         0         0         0         1  11  2015-07-23   
5         0         0         0         1   3  2015-10-07   
6         0         0         0         1  10  2015-07-17   
7         0         0         0         1  20  2015-07-24   
8         0         0         1         0  14  2015-06-07   
9         0         0         0         1   1  2015-07-13   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   
5                     179                51   38                  239.554   
6                     361                52   28                  239.554   
7                     260                50   36                  239.554   
8                     155                12   34                  239.554   
9                     235                11   37                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   
5               31          0         0     0                          2   
6               27          0         1     4                          8   
7               23          0         4     0                          4   
8               25          0         2     0                         40   
9               29          1         1     1                          8   

   Month Value  Day of Week  
0            7            1  
1            7            1  
2            7            2  
3            7            3  
4            7            3  
5           10            2  
6            7            4  
7            7            4  
8            6            6  
9            7            0

In [4]:
# We are going to use a logistic regression 
# Much of this section will be skipped since I have extension knowledge on logistic regression methods 

In [5]:
# Column orders are not the same as the lecture 
data_preprocessed_wrong_order.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'ID', 'Date',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Month Value',
       'Day of Week'], dtype=object)

In [6]:
column_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value', 'Day of Week', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Date', 'ID' ]
data_preprocessed = data_preprocessed_wrong_order[column_names_reordered]
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            1   
1         0         0         0         0            7            1   
2         0         0         0         1            7            2   
3         1         0         0         0            7            3   
4         0         0         0         1            7            3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

         Date  ID  
0  2015-07-07  11  
1  2015-07-14  36  
2  2015-07-15   3  
3  2015-07-16   7  
4  2015-07-23  11

In [7]:
# Drop 2 vars
data_preprocessed = data_preprocessed.drop(['ID', 'Date'], axis = 1)

In [8]:
# Creating our variables
# Lets assume that time spent absent above the median is excessive 
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [9]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']> data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [10]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [11]:
# Include our new array into the data frame
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head(10)

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of Week  \
0         0         0         0         1            7            1   
1         0         0         0         0            7            1   
2         0         0         0         1            7            2   
3         1         0         0         0            7            3   
4         0         0         0         1            7            3   
5         0         0         0         1           10            2   
6         0         0         0         1            7            4   
7         0         0         0         1            7            4   
8         0         0         1         0            6            6   
9         0         0         0         1            7            0   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   
5                     179                51   38                  239.554   
6                     361                52   28                  239.554   
7                     260                50   36                  239.554   
8                     155                12   34                  239.554   
9                     235                11   37                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   
5               31          0         0     0                          2   
6               27          0         1     4                          8   
7               23          0         4     0                          4   
8               25          0         2     0                         40   
9               29          1         1     1                          8   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0  
5                      0  
6                      1  
7                      1  
8                      1  
9                      1

In [12]:
data_preprocessed.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of Week', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours',
       'Excessive Absenteeism'], dtype=object)

In [13]:
# New check point 
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of Week', 
                                            'Daily Work Load Average', 'Distance to Work'], axis =1)
data_with_targets.shape

(700, 12)

In [14]:
# Select the first 14 columns
data_with_targets.iloc[:,0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [15]:
# Skip 1 column in the back 
data_with_targets.iloc[:,0:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [16]:
# Create new variable 
unscaled_inputs = data_with_targets.iloc[:,0:-1]

# Standardize the data 

In [17]:
# First import a tool we can use for this 
from sklearn.preprocessing import StandardScaler

In [18]:
# Now create the standardized scaler
# (i - mean)/std.dev
absenteeism_scaler = StandardScaler()

In [19]:
# Fit the input data
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [20]:
# Apply the scaling mechanism 
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [21]:
# Syntax for transforming it right away: 
# new_data_raw = pd.read_csv('new_data.csv')
# new_data_scaled = absenteeism_scaler.transform(new_raw_data)

In [22]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

## Issue: We don't want standardized dummy variables for interpretation 

In [23]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class
class CustomScaler(BaseEstimator,TransformerMixin):

    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    def __init__(self,columns):   
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler()
        # with some columns 'twist'
        self.columns = columns

    # the fit method, which, again based on StandardScale
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    # the transform method which does the actual scaling
    def transform(self, X, y=None):
        # record the initial order of the columns
        init_col_order = X.columns
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [24]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [25]:
# Remove the dummies 
# columns_to_scale = [ 'Month Value','Day of Week', 'Transportation Expense', 'Distance to Work', 'Age',
       # 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pets']

## Since we moved backward to omit some variables (through backward elimination)
## lets re construct our columns_to_scale in a more intuitive way

In [26]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [27]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [28]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [29]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [30]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [31]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.030796   
1           0         0         0         0     0.030796   
2           0         0         0         1     0.030796   
3           1         0         0         0     0.030796   
4           0         0         0         1     0.030796   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.568019   
696         1         0         0         0    -0.568019   
697         1         0         0         0    -0.568019   
698         0         0         0         1    -0.568019   
699         0         0         0         1    -0.568019   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

# Train-test split of the data

In [32]:
# Over-fitting vs. underfitting
# To avoid over-fitting, hide a small portion of the data 
# You also want to shuffle the data for random selection 

In [33]:
from sklearn.model_selection import train_test_split 

In [34]:
# Split the data 
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 205         0         0         0         1    -0.568019   
 456         0         0         1         0    -0.268611   
 640         0         0         0         1    -1.166834   
 16          0         0         0         1     0.030796   
 431         0         0         0         1     1.527833   
 ..        ...       ...       ...       ...          ...   
 79          0         0         0         1     0.929019   
 312         0         0         0         0     0.929019   
 170         0         0         0         1    -1.166834   
 86          0         0         0         1     0.629611   
 115         0         0         0         1    -0.568019   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 205               -1.016322 -0.379188        -0.408580          0  0.880469   
 456               -0.654143 -1.006686        -1.819793          1 -0.919030   
 640                0.0853

In [35]:
# Array 1: a training data set with inputs (x_train)
# Array 2: a training data set with targets (x_test)
# Array 3: a test data set with inputs (y_train)
# Array 4: a test data set with targets (y_test)
# We also want to size the training vs. test usually 0.8:0.2 is standard 
# Also add an option to shuffle

In [36]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)
# Random_state = 20 makes sure we have the same shuffle each time, instead of new shuffles

In [37]:
print (x_train.shape, y_train.shape)

(560, 11) (560,)


In [38]:
print (x_test.shape, y_test.shape)

(140, 11) (140,)


# Fit a logstic regression

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [40]:
# Training Model 
reg = LogisticRegression()

In [41]:
reg.fit(x_train, y_train)

LogisticRegression()

In [42]:
# Check the model's accuracy
reg.score(x_train, y_train)

0.7767857142857143

In [43]:
# It can classify up to 80% of the observations correctly 

## Manually Check the Accuracy 

In [44]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [45]:
# Compare the elements 
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [46]:
# Total number of matches
np.sum((model_outputs==y_train))

435

In [47]:
# Total number of entries
model_outputs.shape[0]

560

In [48]:
# Check the accuracy again 
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.7767857142857143

# Extracting and exploring the coefficients

In [49]:
# Check the intercept 
reg.intercept_

array([-1.60957471])

In [50]:
reg.coef_

array([[ 2.77151176,  0.93168817,  3.09210221,  0.8090592 ,  0.00781237,
         0.62505482, -0.17390339,  0.28829409, -0.24081615,  0.35753531,
        -0.27337422]])

In [51]:
scaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [52]:
# Everything from sklearn is transformed into nd arrays, and no longer pd frames
# So we need to apply the names
# Note that nd arrays are not in column form, use transpose function
feature_name = unscaled_inputs.columns.values

In [53]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                 Reason_1     2.771512
1                 Reason_2     0.931688
2                 Reason_3     3.092102
3                 Reason_4     0.809059
4              Month Value     0.007812
5   Transportation Expense     0.625055
6                      Age    -0.173903
7          Body Mass Index     0.288294
8                Education    -0.240816
9                 Children     0.357535
10                    Pets    -0.273374

In [54]:
# The intercept is missing 
# And we want it to be in the first row
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table

Feature name  Coefficient
1                 Reason_1     2.771512
2                 Reason_2     0.931688
3                 Reason_3     3.092102
4                 Reason_4     0.809059
5              Month Value     0.007812
6   Transportation Expense     0.625055
7                      Age    -0.173903
8          Body Mass Index     0.288294
9                Education    -0.240816
10                Children     0.357535
11                    Pets    -0.273374
0                Intercept    -1.609575

In [55]:
# Add the odds ratio for easier interpretation 
summary_table['Odds Ratio'] = np.exp(summary_table.Coefficient)
summary_table

Feature name  Coefficient  Odds Ratio
1                 Reason_1     2.771512   15.982778
2                 Reason_2     0.931688    2.538791
3                 Reason_3     3.092102   22.023327
4                 Reason_4     0.809059    2.245794
5              Month Value     0.007812    1.007843
6   Transportation Expense     0.625055    1.868348
7                      Age    -0.173903    0.840378
8          Body Mass Index     0.288294    1.334150
9                Education    -0.240816    0.785986
10                Children     0.357535    1.429801
11                    Pets    -0.273374    0.760808
0                Intercept    -1.609575    0.199973

# Simplifying the model

## Backward Elimination Method

In [56]:
# Generally we remove variables with p-values > 0.05 
# In Machine Learning, they would instead remove the variables with odds ratios close to 1 
# because a 1:1 odds ratio implies no difference 
# The same as a coefficient being close to 0 
# Go back to the data_with_targets checkpoint and remove 
# 'Day of the Week', 'Daily Work Load Average', 'Distance to Work'

# Testing the Machine Learning Model

In [57]:
reg.score(x_test, y_test)

0.7357142857142858

In [58]:
# In the test accuracy, we can expect 74% of employees to be excessively absent 
# In the model accuracy, we had a value of 78% out[48]
# Note: The test accuracy should always be lower due to overfitting!

In [59]:
# Lets take a look at the probabilities 
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.75466347, 0.24533653],
       [0.60917591, 0.39082409],
       [0.48329093, 0.51670907],
       [0.75768232, 0.24231768],
       [0.08357741, 0.91642259],
       [0.3052464 , 0.6947536 ],
       [0.303675  , 0.696325  ],
       [0.11636888, 0.88363112],
       [0.7400284 , 0.2599716 ],
       [0.75596036, 0.24403964],
       [0.50609784, 0.49390216],
       [0.19501503, 0.80498497],
       [0.06248668, 0.93751332],
       [0.7055465 , 0.2944535 ],
       [0.29675526, 0.70324474],
       [0.52028649, 0.47971351],
       [0.50551315, 0.49448685],
       [0.50843643, 0.49156357],
       [0.36713074, 0.63286926],
       [0.06422143, 0.93577857],
       [0.73822433, 0.26177567],
       [0.75768232, 0.24231768],
       [0.47994423, 0.52005577],
       [0.47760936, 0.52239064],
       [0.22619725, 0.77380275],
       [0.74047815, 0.25952185],
       [0.51148533, 0.48851467],
       [0.87702735, 0.12297265],
       [0.24005377, 0.75994623],
       [0.75768232, 0.24231768],
       [0.

In [60]:
# Reshape the array
predicted_proba.shape

(140, 2)

In [61]:
predicted_proba[:,1]

array([0.24533653, 0.39082409, 0.51670907, 0.24231768, 0.91642259,
       0.6947536 , 0.696325  , 0.88363112, 0.2599716 , 0.24403964,
       0.49390216, 0.80498497, 0.93751332, 0.2944535 , 0.70324474,
       0.47971351, 0.49448685, 0.49156357, 0.63286926, 0.93577857,
       0.26177567, 0.24231768, 0.52005577, 0.52239064, 0.77380275,
       0.25952185, 0.48851467, 0.12297265, 0.75994623, 0.24231768,
       0.38859882, 0.71238179, 0.69821485, 0.49507156, 0.24231768,
       0.59772596, 0.26042186, 0.78022686, 0.4398591 , 0.60641126,
       0.24188848, 0.49713003, 0.25862385, 0.40689715, 0.80759194,
       0.59889345, 0.71944702, 0.24317762, 0.24676126, 0.2414598 ,
       0.50180816, 0.29299268, 0.6947536 , 0.24459387, 0.82033268,
       0.39193844, 0.90599346, 0.26442957, 0.32150234, 0.3220128 ,
       0.70502976, 0.69623972, 0.26579672, 0.77584327, 0.24541121,
       0.24490372, 0.07551158, 0.26087263, 0.76176924, 0.29640101,
       0.25772789, 0.31539593, 0.88408057, 0.4387068 , 0.59547

# Saving the model for future deployment 

## Pickle method: a module used to convert a python object into a character stream 

In [62]:
# Save the variable into a new notebook, so we can load it and share it for future use
import pickle

In [63]:
# Syntax: 
# with open('filename', 'write bytes') as file: 
    # pickle.dump(modelname, file)

# dump means save only the model 
# however, we also need to save our absenteeism scaler since it contains the training data
# this way we can preprocess any new data in the same way, prior to feeding it into the algorithm 

In [64]:
with open('model', 'wb') as file: 
    pickle.dump(reg, file)

In [65]:
with open('scaler', 'wb') as file: 
    pickle.dump(absenteeism_scaler, file)

### Next step is creating a mechanism that will load the saved model and make predictions